### ISSUE TITLE
I've got a bug

### ISSUE THREAD

**Issue by Noony-yay** [Noony-yay/website#3]
@zvikabh 
I wrote this code:
https://github.com/Noony-yay/website/blob/d698798b811909769450d10af644f9f9a46ff3a1/fun/09/gps.js#L5-L12
(copied from W3Schools and changed a little)
and for some reason this line:
https://github.com/Noony-yay/website/blob/d698798b811909769450d10af644f9f9a46ff3a1/fun/09/gps.js#L10
doesn't work - I block the location sharing and the parameters are still visible. 
(If it helps, this is the html:
https://github.com/Noony-yay/website/blob/d698798b811909769450d10af644f9f9a46ff3a1/fun/09/index.html#L13-L22
)
Send me a pull request if you manage to solve it!
(By the way, Mom taught me how to open an issue and this is so cool!! I feel so professional!)

**Comment by Noony-yay** [comment]
I updated the css:
https://github.com/Noony-yay/website/blob/2d59054372f6c221dfd5e47bedba1288b79a8669/fun/09/gps.css#L5-L11
And now even the 'cant' line is not turning into display: 'block'...

**Comment by zvikabh** [comment]
I think that line 10 is only reached if your browser doesn't support
location detection. In your case, the browser supports it, but the user
blocked the request. This is reported to you in a different way - using the
second (optional) argument of getCurrentPosition, where you can provide a
separate function that's called in case of location detection error (such
as being blocked by the user). See the documentation at
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

**Comment by Noony-yay** [comment]
Okay, so how do I add it to my code?
Instead of writing:
https://github.com/Noony-yay/website/blob/2d59054372f6c221dfd5e47bedba1288b79a8669/fun/09/index.html#LL13C9-L13C9
Should I write something like:
`<body onload="getLocation(showPosition, cantLoad)>`
?

**Comment by zvikabh** [comment]
Exactly :)

**Comment by Noony-yay** [comment]
And how does the js should look? I'm not sure how to do this... I wrote:
```
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    }
    else {
        cantLoad();
    }
}

function cantLoad(); {
    gid('parameter-container').style.display = 'none';
    gid('cant').style.display = 'block';
}

function showPosition(position) {
    gid('latitude').innerHTML = position.coords.latitude;
    gid('longitude').innerHTML = position.coords.longitude;
    gid('accuracy').innerHTML = position.coords.accuracy;
}
```
And I had two red errors...

Should it be something like:
`GeolocationPositionError(cantLoad);`
Instead of just:
`cantLoad();`?

**Comment by zvikabh** [comment]
- Remove semicolon in the `cantLoad` function definition
- `navigator.geolocation.getCurrentPosition(showPosition, cantLoad);`

**Comment by Noony-yay** [comment]
Okay! I'll try it tomorrow (Lena is upstairs now)
